### ISSUE TITLE
Syerscote BSA breaks patcher

### ISSUE THREAD

**Issue by CloudtheAngel** [SlavicPotato/ied-dev#3]
Hej, when running the Synthesis patcher and having Syerscote SE installed it breaks.
```
System.AggregateException: One or more errors occurred. (Strings section was not able to be read) (Strings section was not able to be read) (Strings section was not able to be read) (Strings section was not able to be read)
 ---> ArchiveException C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Syerscote.bsa: Strings section was not able to be read System.IO.InvalidDataException: Did not end all of its strings in null bytes
   at Mutagen.Bethesda.Archives.Bsa.BsaFileNameBlock.<>c__DisplayClass1_0.<.ctor>b__0()   at Mutagen.Bethesda.Archives.Bsa.BsaFileNameBlock.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Mutagen.Bethesda.Archives.Bsa.BsaFileRecord.GetName()
--- End of stack trace from previous location ---
   at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Lazy`1.CreateValue()
   at Mutagen.Bethesda.Archives.Bsa.BsaFileRecord.get_Path()
   at System.Lazy`1.CreateValue()
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at Mutagen.Bethesda.Archives.Bsa.BsaFileRecord.GetName()
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Lazy`1.PublicationOnlyViaFactory(LazyHelper initializer)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Lazy`1.CreateValue()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at Mutagen.Bethesda.Archives.Bsa.BsaFileRecord.get_Path()
   at ImmersiveEquipmentDisplay.MeshHandler.<>c__DisplayClass20_0.<TransformMeshes>b__2(IArchiveFile candidate) in C:\Users\cloud\AppData\Local\Temp\Synthesis\pbaozlgc.1u4\Git\55z5yoew.c4h\Runner\ImmersiveEquipmentMeshGen\MeshHandler.cs:line 345
   at System.Linq.Parallel.WhereQueryOperator`1.WhereQueryOperatorEnumerator`1.MoveNext(TInputOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at ImmersiveEquipmentDisplay.MeshHandler.TransformMeshes() in C:\Users\cloud\AppData\Local\Temp\Synthesis\pbaozlgc.1u4\Git\55z5yoew.c4h\Runner\ImmersiveEquipmentMeshGen\MeshHandler.cs:line 344
   at ImmersiveEquipmentDisplay.ScriptLess.RunPatch(IPatcherState`2 state) in C:\Users\cloud\AppData\Local\Temp\Synthesis\pbaozlgc.1u4\Git\55z5yoew.c4h\Runner\ImmersiveEquipmentMeshGen\Program.cs:line 60
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 70
```

Although considering it also breaks with the AllGUD patcher uuuuh, maybe it's just an issue with Syerscote, sorry
Proabably shouldn't have posted this

**Comment by SlavicPotato** [comment]
Corrupt BSA
